### ISSUE TITLE
Force Feedback only working with steering wheel attached

### ISSUE THREAD

**Issue by MathiasPechinger** [MrTimcakes/Unity-DirectInput#14]
First of all, thank you for your excellent work!

I don't mean to imply that the absence of the steering wheel is inherently problematic, but for my specific use case, it is.

I am using the Fanatec CSL DD for a bicycle simulator project, where we've replaced the steering wheel with an adapter for bicycle handles. Fortunately, we also purchased the steering wheel, allowing me to confirm that your code functions well! However, we wish to operate the system without the steering wheel attached.

Is there any particular section in the code that requires the steering wheel to be connected, or is this requirement more related to the firmware and specific to the manufacturer?

Thanks again, and have a great day!

**Comment by MrTimcakes** [comment]
Hey,

Unfortunately for your usecase, that's part of the Fanatec firmware. However, there are a couple of ways you could work around it.
If you're not afraid of dealing with microcontrollers you could try [this project](https://github.com/lshachar/Arduino_Fanatec_Wheel) to use an Arduino to communicate with the Fanatec wheelbase via SPI and enable FFB.

Alternately, you can buy a [SimRacingMachines Fanatec Emulator](https://simracingmachines.com/product/tiny-srm-emulator-for-fanatec-wheelbase/) which does the same thing, but you can buy off the shelf.

Thanks for showing interest in the project, and best of luck with your own.

Cheers,
Tim.
