### ISSUE TITLE
[BugReport] _devices does not update if the only device is removed.

### ISSUE THREAD

**Issue by human890209** [MrTimcakes/Unity-DirectInput#3]
![fix](https://user-images.githubusercontent.com/22681924/167283067-8f6c5ebd-1e15-4071-a06f-514c6ab7092f.PNG)

**Comment by human890209** [comment]
MenuItem causes errors during Build. 
![fix2](https://user-images.githubusercontent.com/22681924/167283253-f87912aa-1223-4b59-b4e1-7244c634c1ed.PNG)

**Comment by MrTimcakes** [comment]
Thanks for pointing these out, fixed in v0.5.6
