### ISSUE TITLE
[Help] How to rebind actions across different Directinput devices? 

### ISSUE THREAD

**Issue by human890209** [MrTimcakes/Unity-DirectInput#4]
Hi,
I noticed that different DirectInput devices get different layout names. I want to rebind actions across DirectInput devices but filter none-DirectInput layouts such as regular USB Joystick.
I used Input's control schemes to do that. But the different layout names of di devices block the rebinding.
I change this part to do that.
![di_device](https://user-images.githubusercontent.com/22681924/168708289-c406b0e2-cec4-48a6-8a05-d4483ead2998.PNG)
But this will cause input conflicts if 2+ devices are used simultaneously.

**Comment by human890209** [comment]
I think 2 DirectInput devices with the same device.productName will also cause conflicts. Is there any way to change the device.productName in Windows?

**Comment by human890209** [comment]
I figure it out.
![di_device](https://user-images.githubusercontent.com/22681924/168717368-343ba5f0-59c3-4cf6-99c0-65f39418b27f.PNG)
![rebind](https://user-images.githubusercontent.com/22681924/168717400-3dca5fdd-c515-438a-b1e5-82f4caceb0fc.PNG)

**Comment by MrTimcakes** [comment]
Aah, this is a decision I battled with and even changed through development. I wanted to be able to address multiple DI devices, but also without specifying the exact GUID so bindings could be made and then used by other devices in the same family. I hoped there would be a way to specify exact devices by their serial which is assigned the GUID, but haven't got round to testing that yet.
