### ISSUE TITLE
After build, it runs on a new system and cannot find the DLL

### ISSUE THREAD

**Issue by Senfee-Cheng** [MrTimcakes/Unity-DirectInput#5]
It is normal for me to run on my development machine. Include running in editor

But after I build, the program cannot work normally when running on a new win 64 bit system. Please help me analyze the lo
[Player.log](https://github.com/MrTimcakes/Unity-DirectInput/files/8841375/Player.log)
g

**Comment by AugGust** [comment]
If you installed it via the instructions in the readme (Add package from git URL...), there is a mistake with the package. The DLL you will get is the debug version, which relies on debug version of the VC runtime.

To fix, download the release version of the DLL in the repo, which only relies on VC runtime C++ 2015 redistributable. Close unity, replace the DLL and then open unity again, then build your project.

Ensure that any PC that is running your build now has the VC runtime redistributable installed

**Comment by Senfee-Cheng** [comment]
![图片](https://user-images.githubusercontent.com/20067002/201363349-b8827849-380f-4112-a599-840809d873c2.png)

Do you mean this dll? Is this compiled in release mode?

**Comment by AugGust** [comment]
![image](https://user-images.githubusercontent.com/9332757/201366003-f6c31d42-2414-4bfd-81c1-03b4df841622.png)

**Comment by Senfee-Cheng** [comment]
okay, thank you.
Maybe I can compile and release the release version myself.

**Comment by Senfee-Cheng** [comment]
xcopy /y /d  "$(OutDir)*.dll" "$(SolutionDir)..\Plugin\DLL"

It seems that "\" in front of " *.dll" here did not need "\", because Outdir had already brought "\"

![图片](https://user-images.githubusercontent.com/20067002/201375330-cc048b18-5b67-4e57-b754-7de5e012e485.png)

**Comment by MrTimcakes** [comment]
This is now fixed in v0.6.0, along with a sample of controlling the FFB from the inspector.
