### ISSUE TITLE
Force feedback cannot be triggered

### ISSUE THREAD

**Issue by Senfee-Cheng** [MrTimcakes/Unity-DirectInput#7]
![图片](https://user-images.githubusercontent.com/20067002/203043420-80a8fe9a-eba2-44e7-969e-d10e6ef21dee.png)
![图片](https://user-images.githubusercontent.com/20067002/203043581-c6cf9f7a-6c6a-4f9b-ad3a-b1ff9daf3f09.png)

If you have time, I hope you can upload a sample code called in Unity.

**Comment by MrTimcakes** [comment]
Hey,

Apologies for such a delayed response. From a quick scan of your code snippet, it looks like the spring effect was never enabled prior to being updated. Something you couldn't have known without any documentation to go off. You'll need the line :

`DIManager.EnableFFBEffect(DIManager.devices[0], FFBEffects.Spring);`

In v0.6.0 I've added a sample to control the FFB from the inspector
