### ISSUE TITLE
GPL license is too restrictive

### ISSUE THREAD

**Issue by forestrf** [MrTimcakes/Unity-DirectInput#8]
To be able to use this library, due to the gpl license the whole source code of the game must also be released with a gpl-compatible license.

I don't know if I want to use this as I don't want to test it due to the license.
If the point is to force the release of changes to the source code of this project alone, the lgpl, mozilla or apache license may be better choices.

Thank you.

**Comment by MrTimcakes** [comment]
Hi there,

Thank you for your question about the license for this software library.
You raise an excellent point. The current licence was inherited from my new repo template without much thought.

The license for this project should allow its use within commercial projects, but should also promote modification and pull requests back to the original repo to benefit all users.
Therefore, I believe that the LGPLv3 best suits this project and it's needs.

1. The LGPL is specifically designed for use with software libraries, making it a good fit for our repository. It allows users to modify and distribute the library with the source code for the modified version available. This allows commercial projects to use the library without having to open source their entire project.

2. The LGPL has a "linking exception," which allows users to link to the library from a proprietary program without requiring the proprietary program to be licensed under the LGPL. This means that commercial projects can use the library without worrying about having to open source their entire project.

3. The LGPL is a copyleft license, which means that any modified version of the library must also be licensed under the same terms. This helps to ensure that improvements to the library are shared with the community, and incentivizes contributions in the form of pull requests.

Thanks for bringing this up.
Tim
